「Railsでユーザーフォローを作る」課題提出用プルリクエスト
ot0m1/fjord-books_app pull request #7
Opened 2021-05-05 03:17 UTC by ot0m1

- ユーザー詳細画面にアクセスしてそのユーザーをフォローできるようにする（フォローボタンの設置）
- すでにフォローしてる場合はフォロー解除できるようにする（フォロー解除ボタンの設置）
- 自分自身のユーザー詳細画面ではフォローもフォロー解除もできない
- ユーザー詳細画面に現在のフォロー数（そのユーザーがフォローしているユーザーの人数）とフォロワー数を表示する
- ユーザー詳細画面からフォロー一覧画面に遷移できるようにする
- ユーザー詳細画面からフォロワー一覧画面に遷移できるようにする
- ユーザー詳細画面、フォロー一覧画面、フォロワー一覧画面のスクリーンショットを載せる
- rubocopをパスさせる（要スクリーンショット）

2021-05-26 04:31 UTC, komagata commented on app/helpers/relationships_helper.rb
> +module RelationshipsHelper
実装のないmoduleはファイル自体削除しちゃった方がいいと思います〜

2021-05-26 12:54 UTC, ot0m1 commented on app/helpers/relationships_helper.rb
> +module RelationshipsHelper
確かに不要なファイルと言えそうなので削除しました！

2021-05-27 08:14 UTC, komagata requested changes

2021-05-27 08:14 UTC, komagata commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
Relationshipだと全ての関連はRelationshipと言えてしまうので他の具体的な単語を使った方がいいかもです。（すぐに他の関連も出てきそうなので）

Railsチュートリアルに出てくる名前付けは僕は良く無いと思う部分がいくつかあります。

2021-06-25 13:14 UTC, ot0m1 commented on app/controllers/relationships_controller.rb
> +class RelationshipsController < ApplicationController
確かに関係という単語は抽象度が高くなんにでも当てはまりそうなので`FollowRelationships`という名称に変更しました。

2021-06-27 12:52 UTC, komagata requested changes

2021-06-27 12:52 UTC, komagata commented on app/controllers/follow_relationships_controller.rb
> +class FollowRelationshipsController < ApplicationController
Railsで使うDBは基本的に全てリレーショナルデータベースなので、関連は全てXXXRelationshipと言えてしまうので、別の名前を考えた方が良いと思います。

例えばですが、この場合だったらFriendshipとか。

2021-06-28 12:39 UTC, ot0m1 commented on app/controllers/follow_relationships_controller.rb
> +class FollowRelationshipsController < ApplicationController
なるほど完全に別の名前が望ましいわけですね🙏

言われた名前をそのまま付けるのは思慮が足りないかなと思って他の名前も考えたのですが、他に妥当そうで思いついた名前が Fellowshipt で、これだと fellow と follow が紛らわしそうで、結局そのまま Friendship に変更しました。

2021-06-29 08:07 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-06-29 13:55 UTC, merged